variable "resource_group_name" {
  description = "Resource group name for runtime wiring resources"
  type        = string
}

variable "storage_account_id" {
  description = "Storage account resource ID"
  type        = string
}

variable "key_vault_id" {
  description = "Key Vault resource ID — secrets are stored here for sync-env workflow"
  type        = string
}

variable "managed_identity_principal_id" {
  description = "Principal ID for the user-assigned managed identity"
  type        = string
}

variable "database_url" {
  description = "Full PostgreSQL connection string (postgresql://user:pass@host:5432/db?sslmode=require)"
  type        = string
  sensitive   = true
}

variable "nextauth_secret" {
  description = "NextAuth.js JWT signing secret — generate with: openssl rand -base64 32"
  type        = string
  sensitive   = true
}

variable "entra_client_secret" {
  description = "Entra ID (Azure AD) OAuth2 client secret for NextAuth provider"
  type        = string
  sensitive   = true
}

variable "credential_encryption_key" {
  description = "AES-256 key used to encrypt stored credentials — stored in Key Vault and referenced by Container Apps."
  type        = string
  sensitive   = true
}

variable "local_admin_password" {
  description = "PBKDF2 hash (never the plaintext) of the break-glass local admin password, generated by scripts/Initialize-CnaGitHubSecrets.ps1. Optional: null means the feature is not configured for this environment, and no Key Vault secret is created."
  type        = string
  sensitive   = true
  default     = null
}

variable "secret_expiration_date" {
  description = "RFC3339 expiration timestamp applied to Terraform-managed Key Vault secrets. Must satisfy the 'Enforce-GR-KeyVault' policy (max 90 days from now). The 210 workflow computes this as 'date -u -d +90days'; this default is a local-run fallback."
  type        = string
  default     = "2026-09-20T23:59:59Z"
}
variable "storage_container_ids" {
  description = "List of Storage Container resource IDs for granular role assignment"
  type        = list(string)
  default     = []
  nullable    = false
}
