# Image references are resolved by the deploy workflow from the build manifest
# and passed with -var. No default: a placeholder would plan cleanly and fail
# at pull time, which is exactly the failure the "no default for human-supplied
# values" convention exists to prevent.
variable "api_image" {
  description = "Container image for CNA API (docker.io/<namespace>/cna:api-sha-<7>)"
  type        = string
}

variable "worker_image" {
  description = "Container image for CNA worker (docker.io/<namespace>/cna:worker-sha-<7>)"
  type        = string
}

variable "web_image" {
  description = "Container image for CNA web (docker.io/<namespace>/cna:web-sha-<7>)"
  type        = string
}

variable "tenant_id" {
  description = "Azure tenant ID"
  type        = string
  default     = "00000000-0000-0000-0000-000000000000"
}

variable "location" {
  description = "Azure region for CNA Platform deployment"
  type        = string
  default     = "southcentralus"
}

variable "region_short" {
  description = "Short region code used in resource names (e.g. scus, eus2, wus2)"
  type        = string
  default     = "scus"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "dev"
}

variable "project_name" {
  description = "Project name prefix"
  type        = string
  default     = "cna"
}

# ─── PostgreSQL ────────────────────────────────────────────────────────────────
variable "postgres_admin_username" {
  description = "PostgreSQL administrator username"
  type        = string
  default     = "cnaadmin"
}

variable "postgres_admin_password" {
  description = "PostgreSQL administrator password — set from GitHub Secret CNA_POSTGRES_ADMIN_PASSWORD"
  type        = string
  sensitive   = true
}

# ─── Entra ID (Azure AD) ───────────────────────────────────────────────────────
variable "entra_client_id" {
  description = "Entra ID (Azure AD) application client ID for NextAuth Entra provider"
  type        = string
}

variable "entra_client_secret" {
  description = "Entra ID OAuth2 client secret — set from GitHub Secret CNA_ENTRA_CLIENT_SECRET"
  type        = string
  sensitive   = true
}

# ─── Container Registry ───────────────────────────────────────────────────────
variable "container_registry_username" {
  description = "Username for private container registry image pulls."
  type        = string
  default     = ""
}

variable "container_registry_password" {
  description = "Token or password for private container registry image pulls. Set from GitHub Secret DOCKERHUB_TOKEN for Docker Hub."
  type        = string
  sensitive   = true
}

# ─── NextAuth ─────────────────────────────────────────────────────────────────
variable "nextauth_secret" {
  description = "NextAuth.js JWT signing secret — generate with: openssl rand -base64 32"
  type        = string
  sensitive   = true
}

variable "nextauth_url" {
  description = "Canonical URL of the cna-web deployment (used by NextAuth for callbacks)"
  type        = string
  default     = "https://cna.example.com"
}

variable "web_ingress_ip_security_restrictions" {
  description = "Optional web ingress IP restrictions for direct-origin hardening."
  type = list(object({
    name             = string
    action           = string
    ip_address_range = string
    description      = optional(string)
  }))
  default  = []
  nullable = false
}

# ─── Credential encryption ────────────────────────────────────────────────────
variable "credential_encryption_key" {
  description = "Base64-encoded 32-byte AES-256 key for encrypting SP client secrets at rest. Generate with: openssl rand -base64 32"
  type        = string
  sensitive   = true
}

# ─── Break-glass local admin ──────────────────────────────────────────────────
variable "local_admin_password" {
  description = "PBKDF2 hash (never the plaintext) of the break-glass local admin password, generated by scripts/Initialize-CnaGitHubSecrets.ps1. Optional: leave unset to disable the feature for this environment."
  type        = string
  sensitive   = true
  default     = null
}

# ─── AI Engine + MCP configuration ────────────────────────────────────────────
variable "ai_mode" {
  description = "AI provisioning mode, selected in the deploy workflow's Run-workflow dialog. saas = provision the Foundry/AIServices account, project, chat deployment, private endpoint and RBAC, and inject AZURE_OPENAI_*; byo-api = provision NO cloud AI resources — admins enter Anthropic/OpenAI API keys on /admin/ai-engine (stored AES-256-GCM encrypted in Postgres) and the firewall opens egress to those providers. Flipping a live environment between modes is destructive for the AI resources."
  type        = string
  default     = "saas"
  nullable    = false

  validation {
    condition     = contains(["saas", "byo-api"], var.ai_mode)
    error_message = "ai_mode must be \"saas\" or \"byo-api\"."
  }
}

variable "ai_engine_default" {
  description = "Default global GenAI engine when no ai.activeEngine database setting exists. Must match ai_mode: saas on Azure => azure-openai; byo-api => anthropic or openai (only consulted as the tie-break when both BYO keys are present)."
  type        = string
  default     = "azure-openai"

  validation {
    condition     = contains(["azure-openai", "bedrock", "anthropic", "openai"], var.ai_engine_default)
    error_message = "ai_engine_default must be one of azure-openai, bedrock, anthropic, openai."
  }

  validation {
    condition = (
      var.ai_mode == "saas"
      ? var.ai_engine_default == "azure-openai"
      : contains(["anthropic", "openai"], var.ai_engine_default)
    )
    error_message = "ai_engine_default is incompatible with ai_mode: saas on Azure requires azure-openai; byo-api requires anthropic or openai."
  }
}

variable "foundry_location" {
  description = "Azure region for the Foundry/AIServices account. Defaults to eastus2 (model + capacity availability); override per environment if needed."
  type        = string
  default     = "eastus2"
}

variable "foundry_project_endpoint" {
  description = "Azure AI Foundry project endpoint for the recommendation agent (portal-managed). Empty disables the agent transport; RecommendationEngine then uses the direct MCP clients + offline library."
  type        = string
  default     = ""
}

variable "foundry_recommendation_agent_id" {
  description = "Id of the portal-configured Foundry recommendation agent (MCP tools + instructions). Empty disables the agent transport."
  type        = string
  default     = ""
}

# ─── Azure OpenAI (default engine) ────────────────────────────────────────────
# Points at the gpt-chat-latest deployment on the Foundry/AIServices account.
# Auth is AAD/managed-identity only (key auth is disabled on the account), which
# the app's AzureOpenAI client already uses via DefaultAzureCredential. The
# endpoint is the base host; the AzureOpenAI SDK appends the openai/deployment path.
variable "azure_openai_endpoint" {
  description = "Azure OpenAI base endpoint host for the web app (no /openai/v1 suffix; the SDK appends it)."
  type        = string
  default     = "https://cna-dev-eus2-aif2.services.ai.azure.com"
}

variable "azure_openai_deployment" {
  description = "Azure OpenAI deployment name."
  type        = string
  default     = "gpt-chat-latest"
}

variable "azure_openai_api_version" {
  description = "Azure OpenAI API version."
  type        = string
  default     = "2024-12-01-preview"
}

variable "azure_mcp_endpoint" {
  description = "Azure MCP server endpoint surfaced in cna-web."
  type        = string
  default     = ""
}

variable "azure_mcp_transport" {
  description = "Azure MCP server transport."
  type        = string
  default     = "streamable-http"
}

variable "aws_mcp_endpoint" {
  description = "AWS MCP server endpoint surfaced in cna-web."
  type        = string
  default     = ""
}

variable "aws_mcp_transport" {
  description = "AWS MCP server transport."
  type        = string
  default     = "streamable-http"
}

variable "drawio_mcp_url" {
  description = "draw.io MCP endpoint surfaced in cna-web."
  type        = string
  default     = ""
}

variable "secret_expiration_date" {
  description = "RFC3339 expiry for Terraform-managed KV secrets. Must satisfy Enforce-GR-KeyVault (max 90 days from now). Computed dynamically in CI via 'date -u -d +90days'. No default: a stale hardcoded fallback silently becomes policy-violating once it ages past the 90-day window, so every apply (CI or manual) must pass a freshly computed value."
  type        = string
}
variable "tfstate_resource_group" {
  description = "Resource group hosting the Terraform remote state backend (kept separate from the workload RG to avoid backend/self-destroy lifecycle problems)."
  type        = string
  default     = "rg-cna-dev-scus-tfstate"
}

variable "tfstate_storage_account" {
  description = "Storage account hosting the Terraform remote state container."
  type        = string
  default     = "stcna0512f9tfstate"
}

variable "tfstate_container" {
  description = "Blob container name within the tfstate storage account."
  type        = string
  default     = "tfstate"
}
variable "frontdoor_certificate_pfx_path" {
  description = "File path to the PFX certificate for Front Door"
  type        = string
  default     = null
}

variable "frontdoor_certificate_pfx_password" {
  description = "Password for the PFX certificate"
  type        = string
  sensitive   = true
  default     = null
}

# ─── GitHub ───────────────────────────────────────────────────────────────────
variable "github_owner" {
  description = "GitHub organization or user owning the repository"
  type        = string
}

variable "github_repository" {
  description = "GitHub repository name (without owner)"
  type        = string
}

variable "github_token" {
  description = "GitHub PAT with permissions to manage repository variables"
  type        = string
  sensitive   = true
}
